# Copyright (c) 2025 University of Maryland and the IceCube Collaboration.
# Developed by Taylor St Jean

from typing import Self, Type, TYPE_CHECKING, Union, Sequence, Optional
from pathlib import Path
import time

import torch_geometric as pyg
import torch
import numpy as np

from icegraph.config import IGConfig
from icegraph.data import TrainingDataset, ValidationDataset, TestDataset
from icegraph.data.base import IGData
from icegraph.console import Console

__all__ = ["DatasetRegistry"]


class DatasetRegistry:
    """
    A container class for managing access to training, validation, and test datasets.

    Attributes:
        _train_dataset (TrainingDataset): The training dataset instance.
        _validation_dataset (ValidationDataset): The validation dataset instance.
        _test_dataset (TestDataset): The test dataset instance.
    """

    _dataset_specs: dict[str, tuple[str, Type]] = {
        "train_dataset": ("train", TrainingDataset),
        "val_dataset": ("validation", ValidationDataset),
        "test_dataset": ("test", TestDataset),
    }

    def __init__(
            self,
            train_dataset: TrainingDataset,
            validation_dataset: ValidationDataset,
            test_dataset: TestDataset,
            source: Optional[Union[str, Path, Sequence[Union[str, Path]]]] = None,
            map_file: Optional[Union[str, Path]] = None
    ) -> None:
        """
        Initialize the DatasetRegistry with training, validation, and test datasets.

        Args:
            train_dataset (TrainingDataset): The training dataset.
            validation_dataset (ValidationDataset): The validation dataset.
            test_dataset (TestDataset): The test dataset.
            source (Optional[Union[str, Path, Sequence[Union[str, Path]]]]): Path or list of paths to the LMDB file(s) containing the dataset. Does nothing except save the source to the registry for later access.
            map_file (Optional[Union[str, Path]]): Path to the split mapping file generated by `SplitMapBuilder`. Does nothing except save the source to the registry for later access.
        """
        self._train_dataset = train_dataset
        self._validation_dataset = validation_dataset
        self._test_dataset = test_dataset

        self._datasets = [self._train_dataset, self._validation_dataset, self._test_dataset]

        # register each for later access
        self.source = source
        self.map_file = map_file

        # get training params from config
        self._config = IGConfig.get()

        batch_size = self._config.user_config.training.batch_size
        num_workers = self._config.user_config.training.num_workers

        self.dataloader_kwargs = {
            "batch_size": batch_size,
            "shuffle": True,
            "num_workers": num_workers,
            "multiprocessing_context": torch.multiprocessing.get_context("fork"),
            "pin_memory": torch.cuda.is_available(),
            "persistent_workers": True,
            "prefetch_factor": 4
        }

        # verify the datasets were passed in the correct order
        if self._train_dataset.subset != "train":
            raise ValueError("Expected train_dataset.subset == 'train'")
        if self._validation_dataset.subset != "validation":
            raise ValueError("Expected val_dataset.subset == 'validation'")
        if self._test_dataset.subset != "test":
            raise ValueError("Expected test_dataset.subset == 'test'")

    def __len__(self) -> int:
        """
        Return the number of events in the full dataset.

        Returns:
            int: Number of events.
        """
        return sum(map(len, self._datasets))

    def profile(self, target_samples: int = 50_000, warmup_batches: int = 5) -> None:
        """
        Measure DataLoader throughput (samples/s, MB/s) for PyG batches.
        ONLY the time spent pulling the next batch from the loader is counted.
        Byte measurement happens off-clock so it doesn't affect the timing.

        Args:
            target_samples: stop after at least this many samples
            warmup_batches: discard first N batches to fill worker prefetch
        """

        def _bytes_of_value(v) -> int:
            if torch.is_tensor(v):
                return v.nelement() * v.element_size()
            if isinstance(v, np.ndarray):
                return v.nbytes
            if isinstance(v, (list, tuple)):
                return sum(_bytes_of_value(x) for x in v)
            if isinstance(v, dict):
                return sum(_bytes_of_value(x) for x in v.values())
            return 0

        def _pyg_bytes(data) -> int:
            # Works for both Data and Batch; uses attribute keys exposed by PyG
            total = 0
            for key in data.keys():
                try:
                    val = data[key]
                except Exception:
                    continue
                total += _bytes_of_value(val)
            return total

        loader = self.train_dataloader
        it = iter(loader)

        # --- Warmup (optional, not timed) ---
        for _ in range(warmup_batches):
            try:
                _ = next(it)
            except StopIteration:
                break

        count = 0
        total_bytes = 0
        load_time = 0.0

        while count < target_samples:
            t0 = time.perf_counter()
            try:
                batch = next(it)  # ⬅️ time ONLY the loader fetch/collate/IPC
            except StopIteration:
                break
            t1 = time.perf_counter()
            load_time += (t1 - t0)

            # Off-clock accounting
            batch_size = int(getattr(batch, "num_graphs", 1))
            count += batch_size
            total_bytes += _pyg_bytes(batch)

        # Guard against divide-by-zero
        load_time = max(load_time, 1e-9)

        samples_per_sec = count / load_time
        mb_per_sec = (total_bytes / (1024 ** 2)) / load_time

        Console.out(f"Effective loader throughput: {samples_per_sec:.1f} samples/s")
        Console.out(f"Effective data throughput: {mb_per_sec:.2f} MB/s (off-clock measurement)")

    # --- Static property stubs for type checking and autocompletion ---
    if TYPE_CHECKING:
        @property
        def train_dataset(self) -> TrainingDataset: ...

        @property
        def val_dataset(self) -> ValidationDataset: ...

        @property
        def test_dataset(self) -> TestDataset: ...

    @property
    def train_dataloader(self) -> pyg.loader.DataLoader:
        """
        Returns a Torch Geometric dataloader for the training split.
        """
        return self.train_dataset.dataloader(
            **self.dataloader_kwargs
        )

    @property
    def val_dataloader(self) -> pyg.loader.DataLoader:
        """
        Returns a Torch Geometric dataloader for the validation split.
        """
        return self.val_dataset.dataloader(
            **self.dataloader_kwargs
        )

    @property
    def test_dataloader(self) -> pyg.loader.DataLoader:
        """
        Returns a Torch Geometric dataloader for the test split.
        """
        return self.test_dataset.dataloader(
            **self.dataloader_kwargs
        )

    @classmethod
    def load_from_lmdb(
            cls,
            source: Union[str, Path, Sequence[Union[str, Path]]],
            map_file: Union[str, Path]
    ) -> Self:
        """
        Load datasets from LMDB files and create an instance of the dataset registry.

        Args:
            source (Union[str, Path, Sequence[Union[str, Path]]]): Path or list of paths to the LMDB file(s) containing the dataset.
            map_file (Union[str, Path]): Path to the split mapping file generated by `SplitMapBuilder`.

        Returns:
            Self: An instance of the class initialized with training, validation, and test datasets.
        """
        # configure the base data class
        IGData.configure(source, map_file)

        return cls(TrainingDataset(), ValidationDataset(), TestDataset(), source=source, map_file=map_file)

# --- Dynamically define accessors for splits ---
def _make_dataset_property(attr_name: str, subset_name: str, dataset_cls: Type) -> property:
    """
    Create a property accessor for a dataset corresponding to a specific data split.

    This function returns a @property that retrieves an internal attribute like
    `self._train_dataset`, `self._validation_dataset`, or `self._test_dataset` based on
    the naming convention defined in _dataset_specs.

    Args:
        attr_name (str): Name of the public property (e.g., "training_dataset").
        subset_name (str): The split name used in the internal attribute (e.g., "train").
        dataset_cls (Type): The class of the dataset (e.g., TrainingDataset).

    Returns:
        property: A dynamically constructed @property for accessing the specified dataset.
    """
    def getter(self):
        return getattr(self, f"_{subset_name}_dataset")

    getter.__name__ = attr_name
    getter.__doc__ = f"""
    Accessor for the {subset_name} dataset.

    Returns:
        {dataset_cls.__name__}: The dataset corresponding to the '{subset_name}' split.
    """
    return property(getter)

# Create a property for each dataset type (train, validation, test)
# using naming rules from the _dataset_specs mapping.
for public_name, (subset_name, dataset_cls) in DatasetRegistry._dataset_specs.items():
    setattr(DatasetRegistry, public_name, _make_dataset_property(public_name, subset_name, dataset_cls))

