# Copyright (c) 2025 University of Maryland and the IceCube Collaboration.
# Developed by Taylor St Jean

from abc import ABC, abstractmethod
from pathlib import Path
from typing import TYPE_CHECKING, Optional, Union

import plotly.graph_objects as go
import numpy as np
import torch

from icegraph.config import IGConfig
from icegraph.console import Console

import warnings

# Silence Boost.Python converter warnings
warnings.filterwarnings(
    "ignore",
    category=RuntimeWarning,
    message=r".*to-Python converter for.*already registered.*"
)

if TYPE_CHECKING:
    from icegraph.data.pulses import Pulses
    try:
        from icecube.icetray import OMKey
    except ImportError:
        from icegraph.exceptions import IceCubeImportError
        OMKey = IceCubeImportError.IceCubeMissingBase

__all__ = ["IGDistributionPlot", "IGBasicPlot"]


class IGBasicPlot(ABC):
    """
    Base class for basic plots.
    """
    # plot sizing
    _inner_px = 600
    _pad_px = 80

    # for any colorbar (low saturation steel blue)
    _colorbar = [[0, "rgba(0, 0, 0, 0)"], [0.0001, "#B5CAE6"], [1, "#08519C"]]

    # plot base colors
    _background_color = "#FFFFFF"
    _border_color = "#111111"
    _legend_border_color = "rgba(0, 0, 0, 0.25)"
    _legend_background_color = "rgba(255, 255, 255, 0.7)"

    _grid_color = "#CCCCCC"

    # for simple overlays
    _dark_gray = '#222222'

    # base color (steel blue)
    _color_1 = "#B5CAE6"
    
    # accent 1 (magenta) variations
    _accent_1 = 'rgba(255,45,134,1)'
    _accent_1_opaque = 'rgba(255,45,134,0.85)'
    _accent_1_opaque_fill = 'rgba(255,45,134,0.18)'

    def __init__(self) -> None:
        self._config = IGConfig.get()
        self._fig = go.Figure()

    @abstractmethod
    def _populate_plot(self, x: np.ndarray, y: np.ndarray, nbins: int) -> None:
        """
        Abstract method to populate the plot with subclass-specific logic.

        This method should modify `self._fig`.

        Args:
            x (np.ndarray): X values.
            y (np.ndarray): Y values.
            nbins (int): Number of bins for the heatmap.
        """
        ...

    def plot(self, x: torch.Tensor, y: torch.Tensor, save_path: Optional[Union[str, Path]] = None, **kwargs) -> None:
        """
        This method calls `_populate_plot` to fill in plot data and saves the figure as an HTML file.

        Args:
            x (torch.Tensor): X values.
            y (torch.Tensor): Y values.
            save_path (Optional[Union[str, Path]]): The path where the HTML plot file will be saved.
        """
        self._populate_plot(x.detach().cpu().numpy(), y.detach().cpu().numpy(), nbins=100)

        save_path = Path(
            save_path or
            Path(self._config.user_config.io.default_dir) /
            f"{kwargs.get('title', 'default')}.html"
        )

        if save_path.is_dir():
            save_path = save_path / f"{kwargs.get('title', 'default')}.html"

        self._fig.update_layout(
            **kwargs,
            font=dict(
                size=16
            ),
            plot_bgcolor=self._background_color, paper_bgcolor=self._background_color,
            legend=dict(
                x=0.02, y=0.98, xanchor="left", yanchor="top",
                bgcolor=self._legend_background_color, bordercolor=self._legend_border_color,
                borderwidth=1, orientation="v"
            ),
            width=self._inner_px + self._pad_px + self._pad_px,
            height=self._inner_px + self._pad_px + self._pad_px,
            margin=dict(l=self._pad_px, r=self._pad_px, t=self._pad_px, b=self._pad_px)
        )

        axis_kwargs = dict(
            showgrid=True, gridcolor=self._grid_color, gridwidth=1, zeroline=False,
            showline=True, linecolor=self._border_color, linewidth=1.25, mirror=True
        )
        self._fig.update_xaxes(**axis_kwargs)
        self._fig.update_yaxes(**axis_kwargs)

        self.save(save_path)

    def save(self, save_path: Path):
        """
        Save the current figure as an HTML file.

        Args:
            save_path (Path): The path where the HTML plot file will be saved.
        """
        Console.out(f"Saving plot: {save_path!s}")
        self._fig.write_html(
            save_path,
            config={
                "toImageButtonOptions": {
                    "filename": save_path.with_suffix("").name
                }
            },
            full_html=True,
            include_plotlyjs="cdn",
            include_mathjax="cdn"
        )




class IGDistributionPlot(ABC):
    """
    Abstract base class for generating DOM-level distribution plots using Plotly.

    Subclasses must define the `plot_type` class attribute and implement `_populate_plot`,
    which populates the figure with subclass-specific plotting logic.
    """

    plot_type: Optional[str] = None
    """Defined in each subclass. The plot type generated by the subclass."""

    def __init__(self, pulses: "Pulses") -> None:
        """
        Initialize the plot with user config, an empty Plotly figure, and pulse data.

        Args:
            pulses (Pulses): The pulse data used to generate the plot.

        Raises:
            NotImplementedError: If the subclass does not define the required `plot_type` class attribute.
        """
        self._config = IGConfig.get()

        self._fig = go.Figure()
        self._pulses = pulses

        if self.plot_type is None:
            raise NotImplementedError(
                f"Please define the class attribute 'plot_type' for subclass {self.__class__.__name__}."
            )

    @abstractmethod
    def _populate_plot(self, target_dom: Optional["OMKey"] = None) -> "Pulses.DOMMetadata":
        """
        Abstract method to populate the plot with subclass-specific logic.

        This method should modify `self._fig` using data from the specified DOM,
        and return the associated DOM metadata.

        Args:
            target_dom (Optional[OMKey]): The target DOM to plot. If None, the Pulses object will find the brightest DOM for the selected event.

        Returns:
            (Pulses.DOMMetadata): Metadata associated with the plotted DOM.
        """
        ...

    def plot(self, target_dom: Optional["OMKey"] = None, save_path: Optional[Union[str, Path]] = None) -> None:
        """
        Generate and save a plot for the specified DOM.

        This method calls `_populate_plot` to fill in plot data and saves the figure as an HTML file.

        Args:
            target_dom (Optional[OMKey]): The target DOM to plot. If None, the Pulses object will find the brightest DOM for the selected event.
            save_path (Optional[Union[str, Path]]): The path where the HTML plot file will be saved.
        """
        metadata = self._populate_plot(target_dom)
        dom = metadata.omkey

        save_path = Path(
            save_path or
            Path(self._config.user_config.io.default_dir) /
            f"{self.plot_type.lower()}_plot_{dom.string}.{dom.om}.{dom.pmt}.html"
        )

        self._fig.update_layout(
            font=dict(
                size=16
            ),
            title=(
                f"{self.plot_type} Plot for DOM [{dom.string}, {dom.om}, {dom.pmt}], "
                f"Event/SubEvent ID [{metadata.event_id}/{metadata.sub_event_id}], "
                f"Run/SubRun ID [{metadata.run_id}/{metadata.sub_run_id}], "
                f"SubEventStream [{metadata.sub_event_stream}]"
            )
        )

        self.save(save_path)

    def save(self, save_path: Path):
        """
        Save the current figure as an HTML file.

        Args:
            save_path (Path): The path where the HTML plot file will be saved.
        """
        Console.out(f"Saving {self.plot_type} plot: {save_path!s}")
        self._fig.write_html(save_path, config={
            "toImageButtonOptions": {
                "filename": save_path.with_suffix("").name
            }
        })
