# Copyright (c) 2025 University of Maryland and the IceCube Collaboration.
# Developed by Taylor St Jean

from abc import ABC, abstractmethod
from pathlib import Path
from typing import TYPE_CHECKING, Optional, Union, Sequence

import matplotlib.pyplot as plt
import plotly.graph_objects as go

from icegraph.data import DatasetRegistry
from icegraph.config import IGConfig
from icegraph.console import Console
from icegraph.geometry import Detector

import warnings

# Silence Boost.Python converter warnings
warnings.filterwarnings(
    "ignore",
    category=RuntimeWarning,
    message=r".*to-Python converter for.*already registered.*"
)

if TYPE_CHECKING:
    from icegraph.data.pulses import Pulses
    try:
        from icecube.icetray import OMKey
    except ImportError:
        from icegraph.exceptions import IceCubeImportError
        OMKey = IceCubeImportError.IceCubeMissingBase

__all__ = ["IGDistributionPlot", "IGBasicPlot"]


class IGBasicPlot(ABC):
    """
    Base class for basic plots.
    """

    def __init__(self) -> None:
        self._config = IGConfig.get()
        self._fig = go.Figure()

    @abstractmethod
    def _populate_plot(self, x: Sequence[Union[int, float]], y: Sequence[Union[int, float]]) -> None:
        """
        Abstract method to populate the plot with subclass-specific logic.

        This method should modify `self._fig` using data from the specified DOM,
        and return the associated DOM metadata.

        Args:
            x (Sequence[Union[int, float]): X values.
            y (Sequence[Union[int, float]): Y values.

        Returns:
            (Pulses.DOMMetadata): Metadata associated with the plotted DOM.
        """
        ...

    def plot(self, x: Sequence[Union[int, float]], y: Sequence[Union[int, float]], title: str, save_path: Optional[Union[str, Path]] = None, **kwargs) -> None:
        """
        Generate and save a plot for the specified DOM.

        This method calls `_populate_plot` to fill in plot data and saves the figure as an HTML file.

        Args:
            x (Sequence[Union[int, float]): X values.
            y (Sequence[Union[int, float]): Y values.
            title (str): Plot title.
            save_path (Optional[Union[str, Path]]): The path where the HTML plot file will be saved.
        """
        self._populate_plot(x, y)

        save_path = Path(
            save_path or
            Path(self._config.user_config.io.default_dir) /
            f"{title}.html"
        )

        if save_path.is_dir():
            save_path = save_path / f"{title}.html"

        self._fig.update_layout(
            **kwargs,
            font=dict(
                size=16
            ),
            title=(
                title
            )
        )

        self.save(save_path)

    def save(self, save_path: Path):
        """
        Save the current figure as an HTML file.

        Args:
            save_path (Path): The path where the HTML plot file will be saved.
        """
        Console.out(f"Saving plot: {save_path!s}")
        self._fig.write_html(
            save_path,
            config={
                "toImageButtonOptions": {
                    "filename": save_path.with_suffix("").name
                }
            },
            full_html=True,
            include_plotlyjs="cdn",
            include_mathjax="cdn"
        )




class IGDistributionPlot(ABC):
    """
    Abstract base class for generating DOM-level distribution plots using Plotly.

    Subclasses must define the `plot_type` class attribute and implement `_populate_plot`,
    which populates the figure with subclass-specific plotting logic.
    """

    plot_type: Optional[str] = None
    """Defined in each subclass. The plot type generated by the subclass."""

    def __init__(self, pulses: "Pulses") -> None:
        """
        Initialize the plot with user config, an empty Plotly figure, and pulse data.

        Args:
            pulses (Pulses): The pulse data used to generate the plot.

        Raises:
            NotImplementedError: If the subclass does not define the required `plot_type` class attribute.
        """
        self._config = IGConfig.get()

        self._fig = go.Figure()
        self._pulses = pulses

        if self.plot_type is None:
            raise NotImplementedError(
                f"Please define the class attribute 'plot_type' for subclass {self.__class__.__name__}."
            )

    @abstractmethod
    def _populate_plot(self, target_dom: Optional["OMKey"] = None) -> "Pulses.DOMMetadata":
        """
        Abstract method to populate the plot with subclass-specific logic.

        This method should modify `self._fig` using data from the specified DOM,
        and return the associated DOM metadata.

        Args:
            target_dom (Optional[OMKey]): The target DOM to plot. If None, the Pulses object will find the brightest DOM for the selected event.

        Returns:
            (Pulses.DOMMetadata): Metadata associated with the plotted DOM.
        """
        ...

    def plot(self, target_dom: Optional["OMKey"] = None, save_path: Optional[Union[str, Path]] = None) -> None:
        """
        Generate and save a plot for the specified DOM.

        This method calls `_populate_plot` to fill in plot data and saves the figure as an HTML file.

        Args:
            target_dom (Optional[OMKey]): The target DOM to plot. If None, the Pulses object will find the brightest DOM for the selected event.
            save_path (Optional[Union[str, Path]]): The path where the HTML plot file will be saved.
        """
        metadata = self._populate_plot(target_dom)
        dom = metadata.omkey

        save_path = Path(
            save_path or
            Path(self._config.user_config.io.default_dir) /
            f"{self.plot_type.lower()}_plot_{dom.string}.{dom.om}.{dom.pmt}.html"
        )

        self._fig.update_layout(
            font=dict(
                size=16
            ),
            title=(
                f"{self.plot_type} Plot for DOM [{dom.string}, {dom.om}, {dom.pmt}], "
                f"Event/SubEvent ID [{metadata.event_id}/{metadata.sub_event_id}], "
                f"Run/SubRun ID [{metadata.run_id}/{metadata.sub_run_id}], "
                f"SubEventStream [{metadata.sub_event_stream}]"
            )
        )

        self.save(save_path)

    def save(self, save_path: Path):
        """
        Save the current figure as an HTML file.

        Args:
            save_path (Path): The path where the HTML plot file will be saved.
        """
        Console.out(f"Saving {self.plot_type} plot: {save_path!s}")
        self._fig.write_html(save_path, config={
            "toImageButtonOptions": {
                "filename": save_path.with_suffix("").name
            }
        })
