# file and dir paths
io:
  default_dir: "/data/i3store/users/tstjean/output"
  gcd_path: ""

# frame keys (for feature extraction)
frame_keys:
  header: I3EventHeader
  mctree: I3MCTree_preMuonProp
  bg_mctree: BackgroundI3MCTree
  weight_dict: I3MCWeightDict
  truth_dict: I3MCWeightDict

# table names in the intermediate hdf5 file
table_names:
  features: ml_suite_features
  truth: I3MCWeightDict

data:
  # truth labels to use for training
  target_labels:
    - PrimaryNeutrinoEnergy

  splits:
    weights: {train: 60, val: 20, test: 20}

  normalization:
    apply_log_scaling_x:
      # !!! must be columns present as features (see feature_extraction.feature_config.features
      []
    apply_log_scaling_y:
        # !!! must be columns present under data.target_labels
      - PrimaryNeutrinoEnergy

training:
  seed: 27
  # batch size controls how many samples are loaded into memory at a time in each
  # training batch (see torch_geometric.loader.DataLoader batch_size argument)
  batch_size: 32
  num_workers: 16

  trainer_params:
    max_epochs: 1000
    num_nbrs: 16
    hidden_layers: 3
    hidden_channels: 256
    test_interval_epochs: 1

  normalizer: ZScoreNormalizer

  optimizer:
    learning_rate: 5e-4
    betas: [0.9, 0.999]
    eps: 1e-8
    weight_decay: 5e-5
    amsgrad: False

  tensorboard:
    port: 6006

# ml_suite configurations, see ml_suite docs
feature_extraction:
  # Define name of pulse series from which to extract features
  pulse_key: InIceDSTPulses

  # Define DOM and TimeWindow exclusions. Leave empty if no exclusions
  dom_exclusions:
    exclusions:
      - SaturationWindows
      - BadDomsList
      - CalibrationErrata
    partial_exclusion: true

  # Define pulse modifier to use. Leave empty if pulses are not modified
  pulse_modifier:
    class: ChargeWeightedMeanTimePulseModifier
    kwargs: {}

  # Define configuration for FeatureExtractor
  # (This gets passed on to FeatureExtractorFactory)
  feature_config:

    # Define list of features
    features:
      - class: TotalCharge
        kwargs: {}
      - class: TFirstPulse
        kwargs: {}
      - class: ChargeUntilT
        kwargs:
          times: [10, 50, 100]
      - class: TSpread
      - class: TimeAtChargePercentile
        kwargs:
          percentiles: [0.01, 0.03, 0.05, 0.11, 0.15, 0.2, 0.5, 0.71, 0.8]