seed: 2729
outdir: /data/i3store/users/tstjean/data/test/processed

trainer:
  max_epochs: 10000
  val_interval: 5
  save_interval: 100

services:
  state: { }

  strategy:
    strategy:
      name: regression
      kwargs: { }

  data:
    loader:
      # batch size controls how many samples are passed at a time in each
      # training batch (see torch DataLoader batch_size argument)
      batch_size: 2048
      num_workers: 6
      prefetch_factor: 8
      mp_context: fork
      persistent_workers: true

    sampler:
      name: blockwise
      kwargs:
        block_size: 8192

    module:
      name: graph
      kwargs:
        features: [ ]
        labels:   [ PrimaryEnergy ]
        aux:      [ ]
        # aux is for any non-target labels to include (not used in training), useful for plotting.
        # these labels are served to callbacks by the trainer during validation and test steps

    store:
      name: lru-shard
      kwargs:
        cache_size: 16
        reader:
          name: lmdb
          kwargs: { }

  metrics:
    select:
      - name: mse
        kwargs: { }

      - name: mae
        kwargs: { }

      - name: rmse
        kwargs: { }

components:
  model:
    name: gravnet
    kwargs:
      hidden_layers: 5
      hidden_channels: 256
      num_neighbors: 16
      space_dimensions: 4
      propagate_dimensions: 12

  normalizer:
    name: zscore
    kwargs:
      transforms:
        PrimaryEnergy:
          space: asinh
          base: 10

  optimizer:
    name: adam
    kwargs:
      lr: 0.0002
      weight_decay: 0.00005

  loss:
    name: mse
    kwargs: { }
