# Define name of pulse series from which to extract features
pulse_key: InIceDSTPulses

# Define DOM and TimeWindow exclusions. Leave empty if no exclusions
dom_exclusions:
  exclusions:
  - SaturationWindows
  - BadDomsList
  - CalibrationErrata
  partial_exclusion: true

# Define pulse modifier to use. Leave empty if pulses are not modified
pulse_modifier:
  class: ChargeWeightedMeanTimePulseModifier
  kwargs: {}

# Define configuration for FeatureExtractor
# (This gets passed on to FeatureExtractorFactory)
feature_config:

  # Define list of features
  features:
  - class: TotalCharge
    kwargs: {}
  - class: TFirstPulse
    kwargs: {}
  - class: ChargeUntilT
    kwargs:
      times: [10, 50, 100]
  - class: TSpread
  - class: TimeAtChargePercentile
    kwargs:
      percentiles: [0.01, 0.03, 0.05, 0.11, 0.15, 0.2, 0.5, 0.8]